# Generated by Django 5.0.3 on 2024-04-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_appuser_is_staff_alter_appuser_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseTestCharity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charity_id', models.IntegerField()),
                ('charity_name', models.CharField(max_length=45)),
                ('overview', models.TextField()),
                ('about_charity', models.TextField()),
                ('profile_image', models.BinaryField()),
                ('location_id', models.IntegerField(default=0)),
            ],
        ),
    ]
